name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  linter-psr-12:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@48e0de2ea6fe020804fef2c54f7730e83c24e30d
      with:
        php-version: '8.2'
        extensions: sqlite
    - uses: actions/checkout@v3
    - name: Update composer
      run: composer update
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Clean Install (npm)
      run: |
        npm ci
    - name: Run PSR-12 linter on app/ directory
      run: ./vendor/bin/phpcs --standard=PSR12 app/
    - name: Run PSR-12 linter on config/ directory
      run: ./vendor/bin/phpcs --standard=PSR12 config/
    - name: Run PSR-12 linter on routes/ directory
      run: ./vendor/bin/phpcs --standard=PSR12 routes/
